### ISSUE TITLE
Aligning smart records with routing expressions and reaching v0 milestone for functionality

### ISSUE THREAD

**Issue by petar** [libp2p/go-smart-record#30]
[ ] Tweak design of "reachable" smart tag:
     Usage syntax could be:
         reachable(how=["dialable", "connected"], address=MULTIADDRESS)
     MULTIADDRESS is defined in the routing language spec as "multiaddress(STRING)" and there is a parser for it (which should be used) implemented in github.com/libp2p/go-routing-language/parse/ParseMultiaddress.

[ ] Decouple verification of reachability from the assembly process
     [ ] Redesign Reachable IR node definition to:
          type Reachable struct{
               meta *Meta
               address ma.Multiaddr
               verifyConnected bool
               verifyDialable bool
               verifiedConnected bool // verifiedXXX indicates whether a verification has been performed yet
               verifiedDialable bool
          }
     [ ] Tweak the assembler for reachable to just fill in the above structure (with verifiedXXX = false)
     [ ] Modify the VM's Update method to follow the steps:
          (1) update expression from syntax to IR
          (2) recursively walk through the update IR and:
               (2.1) try to verify any unverified Reachable nodes
               (2.2) if the nodes don't pass verification, erase them from the update IR
               (2.3) if they pass, set the respective verifiedXXX=true
          (3) apply the update IR to the current record for the key in the VM, using current.UpdateWith(updateIR)

[ ] Implement predicate.UpdateWith(update):
     If update is not a predicate or is a predicate with a different tag, then fail. 
     Otherwise, apply the update recursively to:
     - the positional arguments of the predicate (treated as a set, using the update logic for sets)
     - the named arguments of the predicate (treated as a dict, using the update logic for dicts)

At this point, the codebase is in good shape and ready for:
- adding persistence
- adding more commands to the virtual machine (like Set)
We don't need to act on these until necessary.

**Comment by adlrocha** [comment]
Implemented in #31
