### ISSUE TITLE
README missing

### ISSUE THREAD

**Issue by adlrocha** [libp2p/go-smart-record#37]
@petar, do you think it is worth adding a README file with a brief description of the repo before we move on to other things?

**Comment by petar** [comment]
Sure. I wouldn't waste too much time on it though. You could just copy one of the standard ones, e.g. from https://github.com/libp2p/go-libp2p-xor. And just add 3 sentences about what Smart Records are.

**Comment by adlrocha** [comment]
Added here: 4a1b33c6d7cb2fb38d166abc1023fbbbab33b60f
